{% set name = "ctypesgen" %}

package:
  name: {{ name|lower }}-pypdfium2-team
  version: 1.1.1+4_g8a62d02 # this will be later replaced by {{ GGIITT_DESCRIBE_TAG }}+{{ GGIITT_BUILD_STR }}

source:
  git_url: https://github.com/pypdfium2-team/{{ name }}.git
  git_rev: 8a62d02a6fd350df6d22e179bcd164df0da770d4

build:
  entry_points:
    - ctypesgen = ctypesgen.main:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - git  # [not win]
  host:
    - python
    - setuptools >=44
    - wheel
    - setuptools-scm >=3.4.3
    - toml
    - pip
  run:
    - python
  run_constrained:
    - ctypesgen <=0.0.0dev0

test:
  imports:
    - ctypesgen
  commands:
    - pip check
    - ctypesgen --help
  requires:
    - pip

about:
  home: https://github.com/pypdfium2-team/ctypesgen
  summary: Python wrapper generator for ctypes
  description: |
    ctypesgen is a pure-python ctypes wrapper generator. It parses C header files and creates a wrapper for
    libraries based on what it finds.
  license: BSD-2-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://github.com/pypdfium2-team/ctypesgen
  dev_url: https://github.com/pypdfium2-team/ctypesgen

extra:
  recipe-maintainers:
    - boldorider4